# version: '3'

services:
  app:
    build: .
    container_name: app
    environment:
      - NEXTAUTH_SECRET='BU3Hx5A7XzkOZ0XW2vUHnUYZjHcHtXOLxePqLDFAOnQ='
    restart: unless-stopped
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - webnet

networks:
  webnet:

