# version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NEXTAUTH_URL=http://localhost:80
      - NEXTAUTH_SECRET='BU3Hx5A7XzkOZ0XW2vUHnUYZjHcHtXOLxePqLDFAOnQ='
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
